### ISSUE TITLE
Proposal: Add optional header at top of generated code

### ISSUE THREAD

**Issue by cmidgley** [phoddie/compileDataView#14]
It would be nice if the generated code could include a custom header comment.  If we simply allow for the calling code to provide a string that is output at the top of the file, then the cli/web app/manifest could do whatever makes best sense for that application to provide a header.  In the case of the CLI, I'd have it reference a template file so my custom copyright would be included along with a "do not edit this file" comment, and use map template variables for content such as the source filename, date/time, etc.

Not much code on the `compileDataView` side, more work on the CLI or anything that wants to use it intelligently.

**Comment by cmidgley** [comment]
Alternate proposal...

Take any comment header in the source content that exists prior to any pragma or code definition, and inject that into the target file.  This wouldn't allow for template variables, but would keep everything native to the source file and make operation the same between web, manifest and cli.

**Comment by cmidgley** [comment]
New pragma `comment(header | none | all)` added in #15 along with a bunch of other functionality.  Default is `header`.

**Comment by phoddie** [comment]
Closing out as this is now implemented and merged.
