### ISSUE TITLE
proposal: file extension *.cdv.h

### ISSUE THREAD

**Issue by phoddie** [phoddie/compileDataView#17]
compileDataView is intended to accept C language header files. It would be ideal to use a `.h` extension for those files. That makes sense when including the file from C source code. It also helps syntax checkers in editors to know that this is a C compatible header.

But, compileDataView only accepts a subset of valid C header files. It would also be nice to indicate that in the file extension. That is one of the motivations behind the `.cdv` extension used in `example.cdv`. Unfortunately, this extension obscures that this file is also a C header.

TypeScript uses a `.ts` extension for all of its source files, but adds to that for source code files containing only type declarations by using `.d.ts` for the extension. Following that model, I suggest we adopt `.cdv.h` for compileDataView headers. This addresses all the reasons for using `.h` and `.cdv` alone. It also would allow `mcconfig` to easily identify files with as compileDataView sources and automatically invoke compileDataView to compile them as part of a build (work to be done!).

**Comment by cmidgley** [comment]
Logically makes great sense, though one challenge is that the pragmas will be unknown to the C compiler, which usually results in a compile-time warning.  Personally, I go out of my way to eliminate all warnings so any unexpected issue can be caught and not lost amongst "expected" warnings.  But lots of people don't worry about warnings - so it's really a question of what's acceptable to you. 

If pragma warnings are fine, then the easiest solution for sure is to go with `.cdv.h`.  If no warnings, then perhaps keep `.cdv` and come up with a way to generate the `.h` file.

**Comment by phoddie** [comment]
Yea, I prefer to avoid warnings for the same reason you cite. I'd also prefer to avoid generating intermediate files. I suppose compileDataView could implement enough of the preprocessor to allow this kind of thing to work:

```
#if defined(__CDV__)
   #pragma language(typescript)
#endif
```

That opens the door to other uses in the future.

**Comment by cmidgley** [comment]
Interesting idea.  Seems like it could work and not be too difficult if it is kept focused just on this issue (no other macros, no expressions, etc).  It would only be needed by people who are compiling to see, using pragmas, and don't want warnings.

**Comment by phoddie** [comment]
Cool. I like the direction. I should think on it a bt more.

**Comment by phoddie** [comment]
I [committed](https://github.com/phoddie/compileDataView/commit/11ed4035c25894e2aa16e0a4b25471dcd2a270e7) a first pass at #if / #else / #endif. The main goal is to allow this to work:

```
#if defined(__COMPILEDATAVIEW__)
  #pragma whatever1...
#else
  #pragma whatever2...
#endif
```

Nested conditionals and expressions are supported:

```
#if defined(__COMPILEDATAVIEW__) || defined(_gcc__)
  #pragma whatever...
  #if __foo__ > 3
     #pragma more...
  #endif
#endif
```

Evaluation of the if clause combines `Proxy` and `with`, which is bizarre and ill-advised but expedient.

**Comment by phoddie** [comment]
This is done. Basic #if / #else / #endif support is there. `mcconfig` and `mcrun` automatically apply the "cdv" transform for files that end with ".cdv.h".
